### ISSUE TITLE
Trying to improve rdu-async-par without success

### ISSUE THREAD

**Issue by oyundev** [artempyanykh/rdu#1]
Hi Artem, your rdu-async-par implementation works pretty solid and thanks for sharing. 👍 

I tried to improve it explicitly setting worker count in like "[tokio::main(flavor = "multi_thread", worker_threads = 8)]" 
but it didn't improve results, I tried to use walkdir, async-std, rayon etc. but to no avail.

Diskus: https://github.com/sharkdp/diskus (boosted with threads) works faster. I used https://crates.io/crates/may to crate my fastest one in Rust: https://github.com/oyundev/du-rs 

In the end, my go-lang implementation https://github.com/oyundev/du-go proved to be the fastest I could ever come up with.

**Comment by artempyanykh** [comment]
@oyundev hey, just found your post https://www.oyundev.com/post/directory-usage! It's really cool 👍 I had no idea that go's runtime is so fast when it comes to IO.
